# BurntSushi/ripgrep's .github/workflows/ci.yml: test (build stable, rust stable, ubuntu-latest), for the SuperCI scoreboard.
name: SuperCI (GitHub)

on:
  workflow_dispatch: {}

permissions:
  contents: read

env:
  CARGO: cargo
  TARGET_FLAGS:
  TARGET_DIR: ./target
  # Emit backtraces on panics.
  RUST_BACKTRACE: 1

jobs:
  test:
    name: test / github
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install packages (Ubuntu)
        run: |
          ci/ubuntu-install-packages
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Show command used for Cargo
        run: |
          echo "cargo command is: ${{ env.CARGO }}"
          echo "target flag is: ${{ env.TARGET_FLAGS }}"
          echo "target dir is: ${{ env.TARGET_DIR }}"
      - name: Build ripgrep and all crates
        run: ${{ env.CARGO }} build --verbose --workspace ${{ env.TARGET_FLAGS }}
      - name: Build ripgrep with PCRE2
        run: ${{ env.CARGO }} build --verbose --workspace --features pcre2 ${{ env.TARGET_FLAGS }}
      - name: Show build.rs stderr
        shell: bash
        run: |
          set +x
          stderr="$(find "${{ env.TARGET_DIR }}/debug" -name stderr -print0 | xargs -0 ls -t | head -n1)"
          if [ -s "$stderr" ]; then
            echo "===== $stderr ===== "
            cat "$stderr"
            echo "====="
          fi
          set -x
      - name: Run tests with indexing enabled
        run: ${{ env.CARGO }} test --verbose --workspace --features unstable-index ${{ env.TARGET_FLAGS }}
      - name: Run tests with PCRE2 (sans cross)
        run: ${{ env.CARGO }} test --verbose --workspace --features pcre2 ${{ env.TARGET_FLAGS }}
      - name: Test zsh shell completions (Unix, sans cross)
        shell: bash
        run: ci/test-complete
      - name: Print hostname detected by grep-cli crate
        shell: bash
        run: ${{ env.CARGO }} test --manifest-path crates/cli/Cargo.toml ${{ env.TARGET_FLAGS }} --lib print_hostname -- --nocapture
      - name: Print available short flags
        shell: bash
        run: ${{ env.CARGO }} test --bin rg ${{ env.TARGET_FLAGS }} flags::defs::tests::available_shorts -- --nocapture
